services:

  plantdb:
    # PlantDB REST API service, in development mode, served at http://localhost:5000
    build:
      context: ${HOME}/Projects/plantdb
      dockerfile: docker/Dockerfile
    image: roboticsmicrofarms/plantdb:0.14.4
    container_name: plantdb
    command: "fsdb_rest_api --port 5000"
    user: "${UID:-2020}:${GID:-2020}"
    volumes:
      - ${ROMI_DB:-/data/ROMI/shared_fsdb}:/myapp/db
    ports:
      - "5000:5000"

  p3dx:
    # P3DX service, in development mode, served at http://localhost:3000
    build:
      context: ${HOME}/Projects/plant-3d-explorer/
      dockerfile: docker/Dockerfile
      args:
        API_URL: http://localhost:5000
    image: "roboticsmicrofarms/plant-3d-explorer:0.1.2"
    container_name: p3dx
    depends_on:
      - plantdb
    environment:
      REACT_APP_API_URL: http://localhost:5000
    ports:
      - "3000:3000"