# This is a development setup with both 'plantdb' & 'plant-3d-explorer' services in development mode.
# It requires an `.env` file defining values for: `UID`, `GID` & `ROMI_DB`.

services:

  plantdb:
    # PlantDB REST API service, in development mode, served at http://localhost:5000
    image: roboticsmicrofarms/plantdb:0.14.4
    container_name: plantdb
    command: "fsdb_rest_api --port 5000"
    user: "${UID}:${GID}"
    volumes:
      - ${ROMI_DB}:/myapp/db
    ports:
      - "5000:5000"
    healthcheck:
      test: "exit 0"

  plant-3d-explorer:
    # P3DX service, in development mode, served at http://localhost:3000
    image: "roboticsmicrofarms/plant-3d-explorer:0.1.2"
    container_name: p3dx
    depends_on:
      - plantdb
    environment:
      REACT_APP_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
