version: '3'
services:
  plantdb:
    image: "roboticsmicrofarms/plantdb"
    volumes:
      - ${ROMI_DB}:/myapp/db
    ports:
      - "5000:5000"
    healthcheck:
      test: "exit 0"
  plant-3d-explorer:
    image: "roboticsmicrofarms/plant-3d-explorer"
    depends_on:
      - plantdb
    environment:
        REACT_APP_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
