server {
    listen 80;

    # Enable detailed logging
    error_log  /var/log/nginx/error.log debug;
    access_log /var/log/nginx/access.log;

    # Simple configuration to test basic file serving
    location /p3dx/ {
        alias /usr/share/nginx/html/;
        autoindex on;  # Temporarily enable directory listing for debugging
        try_files $uri $uri/ /index.html =404;
    }
}